#!/bin/bash
get_active_sink() {
  pactl list sinks | awk '
    /^Sink #/ { last = substr($2, 2) }
    $1 == "State:" && $2 == "RUNNING" { exit }
    END { print last }
  '
}

get_vol_string() {
    local volume
    volume="$(pamixer --sink "$(get_active_sink)" --get-volume)"'%'

    if [[ $(pamixer --sink "$(get_active_sink)" --get-mute) == 'true' ]]; then
        echo '\uf6a9 '"$volume"
    else
        echo '\uf028 '"$volume"
    fi
}

if [[ -z $1 ]]; then
    get_vol_string;
elif [[ $1 == 'up' ]]; then
    pamixer --sink "$(get_active_sink)" -i 5 --allow-boost
elif [[ $1 == 'down' ]]; then
    pamixer --sink "$(get_active_sink)" -d 5 --allow-boost
elif [[ $1 == 'mute' ]]; then
    pamixer --sink "$(get_active_sink)" --toggle-mute
elif [[ $1 == 'muteon' ]]; then
    pamixer --sink "$(get_active_sink)" -m
elif [[ $1 == 'muteoff' ]]; then
    pamixer --sink "$(get_active_sink)" -u
fi
